version: '2'
services:
  c2s-ui.c2s.com:
    image: bhitsdev/c2s-ui:0.5.0
    volumes:
      - /home/wentao/java/C2S_LOGS/c2s-ui:/java/C2S_LOGS/c2s-ui
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    mem_limit: 1000m
    restart: always

  c2s-ui-api.c2s.com:
    image: bhitsdev/c2s-ui-api:0.5.0
    volumes:
      - /home/wentao/java/C2S_LOGS/c2s-ui-api:/java/C2S_LOGS/c2s-ui-api
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  config-server.c2s.com:
    image: bhits/config-server:0.3.0
    volumes:
      - /home/wentao/java/C2S_LOGS/config-server:/java/C2S_LOGS/config-server
      - /home/wentao/java/C2S_PROPS/c2s-config-data:/java/c2s-config-data
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      spring.cloud.config.server.git.uri: file:/java/c2s-config-data
      security.user.name: name
      security.user.password: password
    restart: always

  context-handler.c2s.com:
    image: bhitsdev/context-handler:2.2.0
    volumes:
      - /home/wentao/java/C2S_LOGS/context-handler:/java/C2S_LOGS/context-handler
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  discovery-server.c2s.com:
    image: bhits/discovery-server:0.11.0
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    volumes:
      - /home/wentao/java/C2S_LOGS/discovery-server:/java/C2S_LOGS/discovery-server
    mem_limit: 1500m
    restart: always

  document-validator.c2s.com:
    image: bhitsdev/document-validator:1.0.0
    volumes:
      - /home/wentao/java/C2S_LOGS/document-validator:/java/C2S_LOGS/document-validator
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      CATALINA_OPTS: -Dspring.profiles.active=docker
    mem_limit: 1500m
    restart: always

  dss.c2s.com:
    image: bhitsdev/dss:2.3.0
    volumes:
      - /home/wentao/java/C2S_LOGS/dss:/java/C2S_LOGS/dss
    mem_limit: 1500m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  edge-server.c2s.com:
    image: bhitsdev/edge-server:0.19.0
    volumes:
      - /home/wentao/java/C2S_LOGS/edge-server:/java/C2S_LOGS/edge-server
      - /home/wentao/java/keystore/edge-server.keystore:/java/keystore/edge-server.keystore
    mem_limit: 1500m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    ports:
      - "3010:80"
      - "3011:443"
    restart: always

  guvnor.c2s.com:
    image: bhits/guvnor:5.5.0
    volumes:
      - /home/wentao/java/C2S_LOGS/guvnor:/java/C2S_LOGS/guvnor
    environment:
      CATALINA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    mem_limit: 1000m
    restart: always

  hapi-fhir.c2s.com:
    image: bhitsdev/hapi-fhir-jpaserver:2.3-01
    environment:
      TZ: "US/Eastern"
      CATALINA_OPTS: -Djdbc.url=jdbc:mysql://hapi-fhir-db.c2s.com:3306/hapi-fhir?autoReconnect=true -Djdbc.password=admin -Xms512m -Xmx700m -Xss1m
    mem_limit: 1000m
    restart: always

  master-ui.c2s.com:
    image: bhitsdev/master-ui:0.1.0
    volumes:
      - /home/wentao/java/C2S_LOGS/master-ui:/java/C2S_LOGS/master-ui
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    mem_limit: 1000m
    restart: always

  master-ui-api.c2s.com:
    image: bhitsdev/master-ui-api:0.1.0
    volumes:
      - /home/wentao/java/C2S_LOGS/master-ui-api:/java/C2S_LOGS/master-ui-api
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  pcm.c2s.com:
    image: bhitsdev/pcm:2.3.0
    volumes:
      - /home/wentao/java/C2S_LOGS/pcm:/java/C2S_LOGS/pcm
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
    mem_limit: 2000m
    restart: always

  pep.c2s.com:
    image: bhitsdev/pep:2.0.0
    volumes:
      - /home/wentao/java/C2S_LOGS/pep:/java/C2S_LOGS/pep
    mem_limit: 1000m
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
    restart: always

  pep-api.c2s.com:
    image: bhitsdev/pep-api:2.0.0
    volumes:
      - /home/wentao/java/C2S_LOGS/pep-api:/java/C2S_LOGS/pep-api
    mem_limit: 1000m
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
    restart: always

  phr.c2s.com:
    image: bhitsdev/phr:2.1.0
    volumes:
      - /home/wentao/java/C2S_LOGS/phr:/java/C2S_LOGS/phr
    mem_limit: 1500m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  pls.c2s.com:
    image: bhitsdev/pls:3.2.0
    environment:
      CATALINA_OPTS: -Xms512m -Xmx2000m -Xss1m
      TZ: "US/Easter"
    mem_limit: 2000m
    volumes:
      - /home/wentao/java/C2S_LOGS/pls:/java/C2S_LOGS/pls
    restart: always

  provider-ui.c2s.com:
     image: bhitsdev/provider-ui:0.2.0
     volumes:
      - /home/wentao/java/C2S_LOGS/provider-ui:/java/C2S_LOGS/provider-ui
     environment:
       JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
       TZ: "US/Eastern"
     mem_limit: 1000m
     restart: always

  provider-ui-api.c2s.com:
     image: bhitsdev/provider-ui-api:0.2.0
     volumes:
       - /home/wentao/java/C2S_LOGS/provider-ui-api:/java/C2S_LOGS/provider-ui-api
     mem_limit: 1000m
     environment:
       JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
       TZ: "US/Eastern"
     restart: always

  staff-ui.c2s.com:
    image: bhitsdev/staff-ui:0.3.0
    volumes:
      - /home/wentao/java/C2S_LOGS/staff-ui:/java/C2S_LOGS/staff-ui
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    mem_limit: 1000m
    restart: always

  staff-ui-api.c2s.com:
    image: bhitsdev/staff-ui-api:0.3.0
    volumes:
      - /home/wentao/java/C2S_LOGS/staff-ui-api:/java/C2S_LOGS/staff-ui-api
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  try-policy.c2s.com:
    image: bhitsdev/try-policy:2.1.0
    volumes:
      - /home/wentao/java/C2S_LOGS/try-policy:/java/C2S_LOGS/try-policy
    mem_limit: 1500m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  uaa.c2s.com:
    image: bhitsdev/uaa:3.4.1-08
    volumes:
      - /home/wentao/java/C2S_LOGS/uaa:/java/C2S_LOGS/uaa
      - /home/wentao/java/C2S_PROPS/uaa/uaa.yml:/java/C2S_PROPS/uaa/uaa.yml
    links:
      - edge-server.c2s.com
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      UAA_DB_PASSSWORD: DONOtSh4r3
      C2S_APP_HOST: edge-server.c2s.com
      C2S_APP_PORT: 80
      C2S_DB_PORT: 3306
      UAA_SMTP_HOST: smtp.gmail.com
      UAA_SMTP_PORT: 587
      UAA_SMTP_USER: w.t.zhou74@gmail.com
      UAA_SMTP_PASSWORD: 123456changeit
    mem_limit: 1500m
    restart: always

  ums.c2s.com:
    image: bhitsdev/ums:0.3.0
    volumes:
      - /home/wentao/java/C2S_LOGS/ums:/java/C2S_LOGS/ums
      - /home/wentao/java/C2S_PROPS/ums:/java/C2S_PROPS/ums
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      spring.datasource.password: admin
    mem_limit: 2000m
    restart: always

  vss.c2s.com:
    image: bhitsdev/vss:0.4.0
    volumes:
      - /home/wentao/java/C2S_LOGS/vss:/java/C2S_LOGS/vss
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
    mem_limit: 2000m
    restart: always

# Database setup

  hapi-fhir-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - hapi-fhir-db-data.c2s.com
    environment:
        TZ: "US/Eastern"
        MYSQL_ROOT_PASSWORD: D0N0tSh4r3
        MYSQL_DATABASE: hapi-fhir
    restart: always

  hapi-fhir-db-data.c2s.com:
    image: busybox
    volumes:
      - /home/wentao/java/mysql/hapi-fhir:/var/lib/mysql

  pcm-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - pcm-db-data.c2s.com
    environment:
        TZ: "US/Eastern"
        MYSQL_ROOT_PASSWORD: D0N0tSh4r3
        MYSQL_DATABASE: pcm
    volumes:
      - /home/wentao/java/C2S_PROPS/pcm:/java/C2S_PROPS/pcm
    restart: always

  pcm-db-data.c2s.com:
    image: busybox
    volumes:
      - /home/wentao/java/mysql/pcm:/var/lib/mysql

  phr-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - phr-db-data.c2s.com
    environment:
        TZ: "US/Eastern"
        MYSQL_ROOT_PASSWORD: D0N0tSh4r3
        MYSQL_DATABASE: phr
    volumes:
      - /home/wentao/java/C2S_PROPS/phr:/java/C2S_PROPS/phr
    restart: always

  phr-db-data.c2s.com:
    image: busybox
    volumes:
      - /home/wentao/java/mysql/phr:/var/lib/mysql

  pls-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - pls-db-data.c2s.com
    environment:
        TZ: "US/Eastern"
        MYSQL_ROOT_PASSWORD: D0N0tSh4r3
        MYSQL_DATABASE: pls
    volumes:
      - /home/wentao/java/C2S_PROPS/pls:/java/C2S_PROPS/pls
    restart: always

  pls-db-data.c2s.com:
    image: busybox
    volumes:
      - /home/wentao/java/mysql/pls:/var/lib/mysql

  uaa-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - uaa-db-data.c2s.com
    environment:
        TZ: "US/Eastern"
        MYSQL_ROOT_PASSWORD: D0N0tSh4r3
        MYSQL_DATABASE: uaa
    restart: always

  uaa-db-data.c2s.com:
    image: busybox
    volumes:
      - /home/wentao/java/mysql/uaa:/var/lib/mysql

  ums-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - ums-db-data.c2s.com
    environment:
        TZ: "US/Eastern"
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: ums
    volumes:
      - /home/wentao/java/C2S_PROPS/ums:/java/C2S_PROPS/ums
    restart: always

  ums-db-data.c2s.com:
    image: busybox
    volumes:
      - /home/wentao/java/mysql/ums:/var/lib/mysql

  vss-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - vss-db-data.c2s.com
    environment:
        TZ: "US/Eastern"
        MYSQL_ROOT_PASSWORD: D0N0tSh4r3
        MYSQL_DATABASE: vss
    volumes:
      - /home/wentao/java/C2S_PROPS/vss:/java/C2S_PROPS/vss
    restart: always

  vss-db-data.c2s.com:
    image: busybox
    volumes:
      - /home/wentao/java/mysql/vss:/var/lib/mysql
